#!/usr/bin/python3
from sys import argv


def factorize(num):

    i = 2

    if value < 2:
        return
    print()
    print(num, "<- value-bef")
    while num % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(num, num / i, i))
    print(num, "<- value-aft")
    print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.split('\n')[0])
            factorize(num)
            line = file.readline()
except:
    pass
